// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpO0foqtTEigp8wUxDbJFnBzhtK3BkWG0',
    appId: '1:36518426934:web:414056f55fdc7ecc25db97',
    messagingSenderId: '36518426934',
    projectId: 'ite-pulsestrength',
    authDomain: 'ite-pulsestrength.firebaseapp.com',
    databaseURL: 'https://ite-pulsestrength-default-rtdb.firebaseio.com',
    storageBucket: 'ite-pulsestrength.firebasestorage.app',
    measurementId: 'G-PQRVN5F5X1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPVqmkMwSy_9LgbJq_aM-6CWEd8iHY-gw',
    appId: '1:36518426934:android:fcff41c5353d044525db97',
    messagingSenderId: '36518426934',
    projectId: 'ite-pulsestrength',
    databaseURL: 'https://ite-pulsestrength-default-rtdb.firebaseio.com',
    storageBucket: 'ite-pulsestrength.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMKax-yl36lKzTv8nn2bRtBVAGVs_k_bM',
    appId: '1:36518426934:ios:8aba8bb7b281ada925db97',
    messagingSenderId: '36518426934',
    projectId: 'ite-pulsestrength',
    databaseURL: 'https://ite-pulsestrength-default-rtdb.firebaseio.com',
    storageBucket: 'ite-pulsestrength.firebasestorage.app',
    iosBundleId: 'com.pulsestrengthproj.pulsestrength',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMKax-yl36lKzTv8nn2bRtBVAGVs_k_bM',
    appId: '1:36518426934:ios:8aba8bb7b281ada925db97',
    messagingSenderId: '36518426934',
    projectId: 'ite-pulsestrength',
    databaseURL: 'https://ite-pulsestrength-default-rtdb.firebaseio.com',
    storageBucket: 'ite-pulsestrength.firebasestorage.app',
    iosBundleId: 'com.pulsestrengthproj.pulsestrength',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpO0foqtTEigp8wUxDbJFnBzhtK3BkWG0',
    appId: '1:36518426934:web:578aa2f08bbe684125db97',
    messagingSenderId: '36518426934',
    projectId: 'ite-pulsestrength',
    authDomain: 'ite-pulsestrength.firebaseapp.com',
    databaseURL: 'https://ite-pulsestrength-default-rtdb.firebaseio.com',
    storageBucket: 'ite-pulsestrength.firebasestorage.app',
    measurementId: 'G-JTYPTYEFX4',
  );
}
